### ISSUE TITLE
`MicrosoftDependencyResolver` seems to forgot disposing `ServiceProvider`

### ISSUE THREAD

**Issue by Akarinnnnn** [EcsRx/SystemsRx#7] opened 2024-06-15 11:54 UTC
https://github.com/EcsRx/SystemsRx/blob/37f8d2d93dc17629da10d734dbdc86cbe60af471/src/SystemsRx.Infrastructure.MicrosoftDependencyInjection/MicrosoftDependencyResolver.cs#L38-L41

Actual type of `IServiceProvider _serviceProvider` is [ServiceProvider](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider?view=net-8.0), which releases resolved services in it's [Dispose()](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider.dispose?view=net-8.0) or [DisposeAsync()](https://learn.microsoft.com/zh-cn/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider.disposeasync?view=net-8.0). Additionally, the provider instance is built by `MicrosoftDependencyRegistry.BuildResolver()`.

**Comment by grofit** [comment] 2024-06-15 13:17
Hmm the problem is the interface `IServiceProvider` doesn't expose the `IDisposable` just the underlying implementation, and I think Microsoft let you provide different implementations if you are using lets say AutoFac via the MS abstractions.

We can possibly add a reflection check or something to see if it implements `IDisposable` as dispose.

**Comment by Akarinnnnn** [comment] 2024-06-15 13:20
Following code might be useful
```csharp
if (_serviceProvider is IDisposable disposableProvider)
    disposableProvider?.Dispose();
```

**Comment by grofit** [comment] 2024-06-15 13:27
Change has been merged in, release is going out now, thanks for reporting.

**Closed as completed by grofit** 2024-06-15 13:27 UTC
